### ISSUE TITLE
Loading Extension crashes SqliteStudio portable

### ISSUE THREAD

**Issue by twoxfh** [pawelsalawa/sqlitestudio#4924] opened 2024-01-27 13:41 UTC
Using SqliteStudio portable 3.4.4 Windows 64, I am attempting to load the Windows 64bit Http Extension from [Alex Garcia](https://github.com/asg017/sqlite-http/releases/tag/v0.1.1) which promptly closes SqliteStudio. I do not see any error messages or any messages in Windows event viewer. Any help is appreciated in debugging the issue or information how I could debug myself. Thanks!

**Comment by pawelsalawa** [comment] 2024-01-27 19:41
Have you tried loading it from an official SQLite command line application, whether it causes the same crash?

**Comment by twoxfh** [comment] 2024-01-27 22:41
> Have you tried loading it from an official SQLite command line application, whether it causes the same crash?

Thanks for looking at this issue.. 

### Success with sqlite3.exe 
Correct If I have sqlite3.exe and sqlite3.dll in the same directory with http0.dll. I can successfully start sqlite3.exe and .load http0 and use the extension. 

### Tried
I cannot load http0 with SqliteStudio even with putting sqlite3.exe with SqliteStudio.exe, sqlite3.dll, and http0.dll in same directory

### Additional information/question
If I load sqlite3.exe in a directory outside of sqlite3.dll and then load the http extension I will get an error saying it cannot find the module (sqlite3.dll). Are there initialization options for SqliteStudio.exe which may link sqlite3.dll in a different way?

**Comment by pawelsalawa** [comment] 2024-01-28 08:42
I requires more investigation.

**Comment by pawelsalawa** [comment] 2024-11-04 18:33
Interestingly enough, the problem seems to affect Windows platform, but not Linux. I have currently no way to verify on MacOS.

**Comment by pawelsalawa** [comment] 2024-11-05 10:35
I can confirm now that this is bug in this loadable extension. It causes SQLite engine to crash when connection with this extension loaded is being closed. I will show proof at the end.

SQLiteStudio crashes when trying to load the extension in Extension Manager, because the Extension Manager has temporary "in-memory" database for loading extesions just to check if they load correctly. Afterwards this database is closed to clean up. Extensions that work correctly are just unloaded at that point, but the `http0` crashes the whole app.

It happens with `sqlite3.exe` too, but you usually don't close connection in `sqlite3.exe` without quitting the app - that's why you don't notice it, but it is possible to enforce closing connection without quitting the app:

```
D:\> sqlite3.exe
SQLite version 3.47.0 2024-10-21 16:30:22
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open xxx.db
sqlite> .connection 1
sqlite> .connection
       0: xxx.db
ACTIVE 1: (memory)
sqlite> .load ./http0
sqlite> .connection 0
sqlite> .connection
ACTIVE 0: xxx.db
       1: (memory)
sqlite> .connection close 1
sqlite>
D:\>
```

I started sqlite3.exe, opened a file database and then I switched to second connection (it's in-memory connection by default). Then I performed the test: load http0, close the connection - at this step the application crashed and quit to shell.

Under Linux this problem doesn't occur.

**Closed** 2024-11-05 10:36 UTC
Labels: bug
