### ISSUE TITLE
Bump cipher_version to 4.2.0

### ISSUE THREAD

**Issue by eklimanov** [pawelsalawa/sqlitestudio#3879] opened 2020-12-07 12:06 UTC
### Details
I use for my database e_sqlcipher 4.2.0_community. But SQLitestudio can't work with this database because it use older sqlcipher version 3.4.2. The version 3.+ is uncompatible with version 4.+. Could you bump version sqlcipher to 4.2.0?

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
Windows 10 (1809)

### SQLiteStudio version
Version 3.2.1

**Comment by pawelsalawa** [comment] 2020-12-09 11:48
Duplicate of #3494

**Closed by pawelsalawa** 2020-12-09 11:48 UTC
