### ISSUE TITLE
Column Widths resize

### ISSUE THREAD

**Issue by nexcentric** [pawelsalawa/sqlitestudio#4071] opened 2021-04-17 20:58 UTC
Please make it that the column width doesn't readjust to be lower than the column name or the column content.
I saw this same issue has been reported few times, since 2018, but the issue was closed without a solution.

Thanks for this great tool ;)

**Comment by pawelsalawa** [comment] 2021-04-17 21:37
Have you already used 3.3.3 or at least 3.3.2?

**Comment by pawelsalawa** [comment] 2021-04-17 21:39
I think #3447 is about the same thing (and even more). Is it?

**Comment by nexcentric** [comment] 2021-04-18 06:49
> Have you already used 3.3.3 or at least 3.3.2?

Yes, I'm using 3.3.2. and I checked 3.3.3 patch notes before posting.



> I think #3447 is about the same thing (and even more). Is it?

yes.

**Comment by pawelsalawa** [comment] 2021-04-18 08:40
Duplicate of #3447

**Comment by pawelsalawa** [comment] 2021-04-25 15:30
I've closed #3447 because as far as I tested it now, the 3.3.x series is behaving exactly as expected there and I believe it is also expected here.

I would like to clarify what is wrong right now, because as far as I tested it, columns initially have width necessary to fit column header or its contents (whichever is longer). The only exception is if column has very long value - in that case the column (initial) width is limited to reasonable size, so one column doesn't occupy whole screen.

Haveing that said - what did you expect to work differently here?

**Comment by nexcentric** [comment] 2021-04-26 05:48
I would add next options:

1. Column width should not hide column name. [false/true]
2. Column width should not hide column content. [false/true]
3. Column max auto size width: 0-x

*I added a pic example of the issue right now.
![Capture](https://user-images.githubusercontent.com/56408907/116034441-91061480-a663-11eb-9783-d6b4a4c868f9.PNG)

You can see there are columns you can't read, and it is a pain to go one by one manually setting its width. But even worse is that every time you restart sqlitestudio, you have to do it again...

**Comment by pawelsalawa** [comment] 2021-04-26 12:11
I see. The problem manifests itself if we deal with a lot of columns. If there are just few, or a dozen, it works fine.

Good. I reproduced it and now I can do something about it.

**Closed** 2021-10-01 07:33 UTC
Labels: bug
