### ISSUE TITLE
Support for relations with foreign keys

### ISSUE THREAD

**Issue by can333** [pawelsalawa/sqlitestudio#5138] opened 2024-11-29 12:47 UTC
### Details
SQLite also supports releations with foreign keys between tables.  Would be great to visualize this with a graphical representation 
![Screenshot_2024-11-29_13-42-01](https://github.com/user-attachments/assets/564da645-23e5-4a3c-bba2-5a7f03782080)
(see attached example).

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment] 2024-11-29 12:52
Duplicate of #2865

**Closed by pawelsalawa** 2024-11-29 12:52 UTC
