### ISSUE TITLE
Renaming columns in tables with (SpatiaLite) triggers

### ISSUE THREAD

**Issue by ar-jan** [pawelsalawa/sqlitestudio#3276] opened 2018-02-12 13:27 UTC
### Details
I tried to rename columns in a database with SpatiaLite enabled, but received some warnings:

> Cannot not update trigger gii_tablename_GEOMETRY according to table tablename modification.
> There is a problem with updating an DELETE statement within gii_tablename_GEOMETRY trigger. One of the DELETE substatements which might be referring to table tablename cannot be properly modified. Manual update of the trigger may be necessary.

Is renaming columns in tables with triggers supported, or could it be supported?

### Steps to reproduce
Create a SpatiaLite database, then try to rename a column.

### Operating system
Windows 7

### SQLiteStudio version
3.1.1

**Comment by pawelsalawa** [comment] 2018-02-12 15:37
If I remember correctly, such message appears as a warning but you can still proceed. It's just that you will need to adjust that gii_tablename_GEOMETRY trigger code (if needed) afterwards, because SQLiteStudio failed to analyze it (for whatever reason).

Of course SQLiteStudio should assist you as much as possible to automate this process, so you don't have to do anything manually. Usually it works fine. This case is somehow problematic and you can help debugging it. Best way would be if you could:

1. share a sample database to reproduce the problem (you can attach files to comments here on github)
2. tell which column & table in that database are you trying to rename?

**Comment by ar-jan** [comment] 2018-02-13 17:11
Attached is an export of the structure for a SpatiaLite database (created in QGIS). Or should I attach the database itself? (It's not exactly a minimal example since there are so many tables/etc. defined for SpatiaLite). In this case, there's only one custom table `mytest`; trying to rename the `name` column triggers the problem.

[test_spatialite.sql.txt](https://github.com/pawelsalawa/sqlitestudio/files/1720824/test_spatialite.sql.txt)

P.S. Thanks for the awesome software, by the way.

**Comment by pawelsalawa** [comment] 2018-02-13 22:20
Thanks. I managed to reproduce the problem, so I should be able to fix it.

I restored the DB and removed most of the tables to minimize the reproducible example. Attaching file here for further reference.

**Comment by pawelsalawa** [comment] 2018-02-13 22:22
Btw @ar-jan how do you work with SpatiaLite under SQLiteStudio? Do you replace sqlite3.dll with the one from SpatiaLite, or somehow different?

**Comment by ar-jan** [comment] 2018-02-14 11:59
I was testing whether I could work with it in SQLiteStudio, seeing what does and doesn't work and if there's at least no corruption of the db. So far I just used SQLiteStudio as-is. I don't need the spatial funtionality there, I was interested in using it for renaming/reordering columns and tables, and editing/creating textual attributes residing in the same database.

**Comment by pawelsalawa** [comment] 2018-06-08 10:13
After deep investigation it turned out that the issues are indeed caused by missing SpatiaLite implementation in the database connection. Therefore it won't be fixed until SQLite supports SpatiaLite plugin. Created feature request for the same: #3335

**Closed by pawelsalawa** 2018-06-08 10:13 UTC
Labels: bug

**Comment by ar-jan** [comment] 2018-06-08 10:36
Thanks for looking into this!
