### ISSUE TITLE
Right-click on 'Data' of Empty Table Closes App

### ISSUE THREAD

**Issue by TomaszWlodarczyk** [pawelsalawa/sqlitestudio#3981] opened 2021-02-17 22:07 UTC
### Details
Application Crashes when righ-click on 'Data' tab of newly cretaed table (with no records).

### Steps to reproduce
Create new table, create column, save, go to 'Data' tab, right-click mouse.

### Operating system
Win10-64

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment] 2021-02-17 22:44
Duplicate of #3474
Fixed for upcoming 3.3.0.

**Closed by pawelsalawa** 2021-02-17 22:44 UTC
