### ISSUE TITLE
SQLite **Select * from View** adds on additional columns "ResCol 0"

### ISSUE THREAD

**Issue by TerrenceJoy** [pawelsalawa/sqlitestudio#3781] opened 2020-05-30 01:44 UTC
### Details
I understand that this issue was reported earlier, and i see that you had closed the issue saying the bug was fixed. But i happened to come across the issue again. it took me a while to identify the issue. 
### Steps to reproduce
When i tried to use the _Union All_ option on two different Views, which had the same set of columns, it always threw an error as mentioned below. and then when I ran the Select queries separately on both Views, it had the **ResCol 0** and **ResCol  1** as shown in the image below. 

> "[06:39:36] Error while executing SQL query on database 'tasklib': no such column: Vw_CustomView_TaskList_Items.custom_id"

### SQLiteStudio **version**
SQLite Studio 3.2.1

![image](https://user-images.githubusercontent.com/53968116/83316540-fb3fea80-a243-11ea-804e-24f3b8849389.png)

**Comment by pawelsalawa** [comment] 2020-05-30 09:20
Mentioned issue #3446 

Okay. If it's fixed for 3.2.2, what are you expecting here?

**Comment by TerrenceJoy** [comment] 2020-06-01 13:32
I was looking for a solution, but couldn't find one online anywhere and when i saw a similar discussion status as defect closed, and since it was an article from 2018, I was was curious to check.  (my bad, i failed to notice it to be for the 3.2.2) Thanks for your time. Will wait for the 3.2.2 to be out.

**Comment by pawelsalawa** [comment] 2020-06-01 13:46
Duplicate of #3446

**Closed** 2020-06-01 13:46 UTC
Labels: discussion

**Comment by pawelsalawa** [comment] 2024-09-01 20:59
Is your View very complex? I'm asking, cause if it's simple and you can share it's code, it would be easier to reproduce, in order to fix it.
