### ISSUE TITLE
DB/ER Diagrams 

### ISSUE THREAD

**Issue by TerrenceCJoy** [pawelsalawa/sqlitestudio#4471] opened 2022-07-14 05:13 UTC
### Details
It would be great to see an option to create DB or ER diagrams from SQLite studio. Most of the Projects requires developers to produce the ER diagrams. also ER diagrams makes it easy to view the DBs you are working with and plan ahead. this feature added to SQLite studio would be of great use.

**Comment by pawelsalawa** [comment] 2022-07-16 08:54
Duplicate of #2865

**Closed by pawelsalawa** 2022-07-16 08:54 UTC
