### ISSUE TITLE
Saving view removes comments

### ISSUE THREAD

**Issue by RaptorX** [pawelsalawa/sqlitestudio#4530] opened 2022-10-21 19:47 UTC
### Details
When making changes to a view, comments are removed from the beginning of the query and after the last semicolon.
This makes it hard to document certain things in views.

### Steps to reproduce
* Create a view
* Add a single line comment or a multiline comment
* create a simple query
* end your query with semicolon
* Add a single line comment or a multiline comment
* Save your query

```
-- This comment will disapear

/*
    This comment will disappear too 
*/

SELECT BreederInfo.Loft AS Breeders,
       InitialBirdsSent.entries AS [Race entry]
  FROM InitialBirdsSent
       JOIN BreederInfo ON InitialBirdsSent.Bid = BreederInfo.bid
 WHERE BreederInfo.bid IN (
           SELECT QualifiedBreeders.Bid
             FROM QualifiedBreeders
       );

-- All of this will be gone:
       
/*
    This table lists how many birds per breeder were reported as sent.
    
    It only takes into account Qualified Breeders.
    
    Qualified Breeders are breeders that have sent at least 15 birds accross a minimum of 3 Championships.
    All the other tables are reported only on Qualified Breeders too.
*/
```

### Result
All your comments get deleted

### Notes
If you add a comment at the end of your query but dont use semicolon to finish your query
the comment will stay saved.

```
SELECT BreederInfo.Loft AS Breeders,
       InitialBirdsSent.entries AS [Race entry]
  FROM InitialBirdsSent
       JOIN BreederInfo ON InitialBirdsSent.Bid = BreederInfo.bid
 WHERE BreederInfo.bid IN (
           SELECT QualifiedBreeders.Bid
             FROM QualifiedBreeders
       ) -- notice the lack of a semicolon
-- the following comments will not disappear
/*
    This table lists how many birds per breeder were reported as sent.
    
    It only takes into account Qualified Breeders.
    
    Qualified Breeders are breeders that have sent at least 15 birds accross a minimum of 3 Championships.
    All the other tables are reported only on Qualified Breeders too.
*/
```

### Operating system
Win10 64bit

### SQLiteStudio version
3.3.3

**Comment by pawelsalawa** [comment] 2022-10-21 19:53
Duplicate of #3079

**Closed by pawelsalawa** 2022-10-21 19:53 UTC

**Comment by RaptorX** [comment] 2022-10-21 19:59
They are different views so I'm not sure if the same conditions apply but I'll go ahead and document the specific steps on that post as well.

Because I noticed that not all comments are deleted.

**Comment by pawelsalawa** [comment] 2022-10-21 20:01
This is a general problem of comments removal by SQL code formatters. When this is addressed, comments will remain in all places.
