### ISSUE TITLE
rowid required when select * from some_view

### ISSUE THREAD

**Issue by topchyan** [pawelsalawa/sqlitestudio#4720] opened 2023-03-11 14:41 UTC
In 3.4.3 now when running a select * from a given view, which doesn't explicitly show a column RowID the tool now throws an error:

![image](https://user-images.githubusercontent.com/16518288/224490516-acfa645b-5b74-4fbd-93f3-e0fe980b66db.png)

**`[09:27:34] Error while executing SQL query on database 'audit': no such column: DTL_vw.ROWID`**

Adding this column to the view gets rid of this error.

![image](https://user-images.githubusercontent.com/16518288/224490602-338701ad-c722-4773-a78d-92f51f5a4845.png)

![image](https://user-images.githubusercontent.com/16518288/224490727-6e35a447-46a7-47b3-b976-3cc0babf2454.png)

I think this is a serious flaw that should be addressed, since adding RowID to each view was never a requirement.

**Comment by pawelsalawa** [comment] 2023-03-22 21:00
I'm unable to reproduce this problem. Would you be willing to share schema of this view and all tables it uses (excluding the data)?

**Comment by goyometeojorito** [comment] 2023-03-30 09:20
An example (The query works if table "Users" with row "Id" exists): 

SELECT (SELECT Id FROM AnotherTable ORDER BY Id LIMIT 1) As SubQ FROM Users 

This NOT Work:

SELECT T.* 
FROM 
(
    SELECT (SELECT Id FROM AnotherTable ORDER BY Id LIMIT 1) As SubQ FROM Users 
) T

Boths queries must returns the same result.

**Comment by pawelsalawa** [comment] 2023-04-03 22:01
Okay, I confirmed that the example above indeed fails (with the `ROWID` message) in 3.4.3. Good news is that the version in current master branch already executes it correctly, so I'm closing it.

**Closed by pawelsalawa** 2023-04-03 22:01 UTC
Labels: bug, pending-clarification

**Comment by topchyan** [comment] 2023-04-04 15:35
> Okay, I confirmed that the example above indeed fails (with the `ROWID` message) in 3.4.3. Good news is that the version in current master branch already executes it correctly, so I'm closing it.

So this will be fixed in 3.4.4?
