### ISSUE TITLE
ORDER of columns of the tables in the treeview

### ISSUE THREAD

**Issue by Raphael-MOUQUIN** [pawelsalawa/sqlitestudio#4151] opened 2021-07-05 16:08 UTC
### Details
**ORDER of columns** of the tables:
In the treeview we have alphabetical ASCENDING order , 
In the Structure tab, DIFFERENT order than the one in the treeview

<img width="308" alt="scrshot_SQLiteStudio3 3 3_COLUMNS_ORDER" src="https://user-images.githubusercontent.com/86474028/124497691-854d7180-ddbb-11eb-8703-7698b6de46ce.PNG">

### Steps to reproduce
Issue apply to all tables/columns. Functionnality always active.

### Operating system
Win7

### SQLiteStudio version
3.3.3

**Comment by Raphael-MOUQUIN** [comment] 2021-07-06 15:22
Funny same functionnality  :) with  your twin-brother DB Browser for SQLit .
 but the same issue/functionnality  exists  with your better-than-ever SQLiteStudio . THANKS to you and for what you do and give to other. GʘD Bless You and have a great day/time/life

Best Regards
Raphael

--

Mr Salawa @pawelsalawa  , my apologizes , i'm sorry , i got confused the screenshot is the GUI of DB Browser for SQLite v.3.12.1 on Win7

so yes keep this issue open , 

Screenshot above of the DB Browser for SQLite v.3.12.1 on Win7 :  :
<img width="320" alt="scrshot_DB Browser for SQLiteStudio-3 12 1_ABOUT_POPUP" src="https://user-images.githubusercontent.com/86474028/124625087-c9a14600-de7d-11eb-9c0e-217b199dacb8.PNG">

**Comment by tuffnatty** [comment] 2023-03-17 14:41
Duplicate of #4085

**Comment by pawelsalawa** [comment] 2023-03-17 15:23
A duplicate, indeed.

**Closed by pawelsalawa** 2023-03-17 15:23 UTC
