### ISSUE TITLE
sql is now blacked out

### ISSUE THREAD

**Issue by mwbidwell** [pawelsalawa/sqlitestudio#5116] opened 2024-11-22 23:25 UTC
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by pawelsalawa** [comment] 2024-11-22 23:29
Duplicate of #5114.
Will be fixed in 3.4.6 (to be released soon).

**Closed by pawelsalawa** 2024-11-22 23:29 UTC
