### ISSUE TITLE
[Enhancement] Add support for "strict tables"

### ISSUE THREAD

**Issue by l3oxy** [pawelsalawa/sqlitestudio#4498] opened 2022-08-28 18:42 UTC
### Details
During table creation, it'd be cool if, similar to the "WITHOUT ROWID" checkbox, that there was also a "STRICT TABLE" or "STRICT" checkbox.

Official documentation on strict tables: https://www.sqlite.org/stricttables.htm

The affect on DDL would be to append "STRICT" to the CREATE TABLE command, after the ")".
Per the documentation, if both are checked, then the DDL would need to comma-separate the "WITHOUT ROWID" and the "STRICT".

Attached is an image of the part where one creates a table, and it shows the "WITHOUT ROWID" checkbox. 
I'm thinking just add another checkbox to the right of it with label "STRICT TABLE" or "STRICT".
<img width="856" alt="Screen Shot 2022-08-28 at 13 33 12" src="https://user-images.githubusercontent.com/42228543/187089381-424e8b63-b8cc-4063-bf82-d8d89079d07c.png">
l

**Comment by pawelsalawa** [comment] 2022-08-28 19:01
Duplicate of #4058

**Closed by pawelsalawa** 2022-08-28 19:01 UTC
