### ISSUE TITLE
Column data is replaced by text in SELECT query. 

### ISSUE THREAD

**Issue by Priskvark** [pawelsalawa/sqlitestudio#4549] opened 2022-11-17 01:52 UTC
The SELECT item does not contain data if “AS” is specified in the first SELECT statement (for a Key field?).

Instead, the columns in every row in the output are filled with the text specified in the AS clause.

For example:
SELECT Mytable.UgglynameID AS 'Nice NameID', 
MyTable.Item2 AS ‘Second item’
FROM Whatever;

Is displayed for all rowes presented:

|Nice NameID |2|
|Nice NameID |354|
|Nice NameID |1023|
…

I can see the same issue for some Count … AS

The really bad thing about this is that in some queries everything just works fine and I can not tell why.

I am running SQLiteStudio 3.4.0 on Windows 10 Pro 22H2

**Comment by pawelsalawa** [comment] 2022-11-17 07:04
Id does not really hapen for me. Can you share the DDL of your table on which you execute the query on?

**Comment by pawelsalawa** [comment] 2022-11-17 22:45
I completely understand the hesitation towards publishing your queries. Still, I'm not able to reproduce the issue. Would you be willing to send a query to support@sqlitestudio.pl? (I'll be the only one to see it)

**Comment by Priskvark** [comment] 2022-11-17 23:45
I posted the requested query to support mail. 

A question to ask is if there is something wrong in my environment? Anyway, I hope you sort things out.

**Comment by pawelsalawa** [comment] 2022-11-18 21:20
I managed to reproduce and fix the issue. I'll soon push it into the repo. It will be released in 3.4.1 (I plan to release it in days).

**Closed** 2022-11-18 21:24 UTC
Labels: bug
