### ISSUE TITLE
Left-hand pane keeps resetting

### ISSUE THREAD

**Issue by johannes1971** [pawelsalawa/sqlitestudio#3784] opened 2020-06-02 08:02 UTC
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by johannes1971** [comment] 2020-06-02 08:03
The left-had pane (containing the databases and tables) comes up with a size that shows the first character of every table name, and nothing else. I can resize it, but doing anything (like inspecting a table) will immediately revert the size to the original too-small size.

**Comment by johannes1971** [comment] 2020-06-02 08:03
Running the application a second time, I cannot reproduce the problem anymore.

**Comment by pawelsalawa** [comment] 2020-06-02 08:36
Duplicate of #3421

**Closed** 2020-06-02 08:37 UTC
