### ISSUE TITLE
No error details when open locked database

### ISSUE THREAD

**Issue by zeliboba7** [pawelsalawa/sqlitestudio#4387] opened 2022-01-29 09:45 UTC
### Details
When someone wants to open locked database, there is no information why it cannot be opened. When push button "Test connection" only shows error (exclamation sign), but no details. When push "Ok" button an error message "Could not add database places.sqlite:" appeared, but again no details. On the other hand when try to open it with command line utility sqlite3, e.g. "sqlite3 places.sqlite .schema" it shows message "Error: database is locked" which is very informative.

### Steps to reproduce
1. Run SqliteStudio
2. In menu Database -> Add database
3. Choose locked database, e.g. places.sqlite from profile of running firefox browser
4. Push "Test connection" and "Ok" button

**Comment by pawelsalawa** [comment] 2022-01-30 00:23
Duplicate of #4341

**Closed by pawelsalawa** 2022-01-30 00:23 UTC
