### ISSUE TITLE
Refresh DB Tree After Execute From File

### ISSUE THREAD

**Issue by HatEmU** [pawelsalawa/sqlitestudio#3773] opened 2020-05-22 22:29 UTC
### Details
When I create a SQLite database and populate it by choosing the context menu option "Execute SQL From File" and getting a success notification the DB tree doesn't refresh to show the tables, views, etc. that were added from the SQL file.

Note: When I export a database to a SQL format from SQLite studio the resulting file contains the SQL commands `BEGIN TRANSACTION;` and `COMMIT TRANSACTION;` These commands cause an error when executing the file inside SQLite studio using the "Execute SQL From File" because I think that context menu option also executes a `BEGIN TRANSACTION;` of its own and they conflict and result in an error

### Steps to reproduce
Create a database on the file system or the memory inside SQLite studio and right click on the database in the database tree to bring up the context menu and select a SQL file to execute.

### Operating system
Windows 10 Pro 64 bit

### SQLiteStudio version
3.2.1

**Comment by HatEmU** [comment] 2020-05-22 22:31
I wanted to make a pull request to fix this but the code lacks comments and I got pretty lost trying to figure out where everything is.

**Comment by pawelsalawa** [comment] 2020-05-22 22:52
Duplicate of #3773

**Closed by pawelsalawa** 2020-05-22 22:52 UTC
