### ISSUE TITLE
The width of database browser pane at left side always shrink automatically.

### ISSUE THREAD

**Issue by RENSting** [pawelsalawa/sqlitestudio#3910] opened 2021-01-15 06:00 UTC
### Details
I have enlarged the width of database browser pane for displaying all objects, then, I switch to other application to do some tasks, after that, I switch back the sqlite-studio and I found that the width of left pane shrink into original size automatically.
I think that it would be better to keep the size of left pane in previous value.
Thanks.

### Steps to reproduce
1. enlarge the width of database browser pane;
2. open another application like MS-Word;
3. do something in that application;
4. switch back studio via click the icon on task bar;
5. you can find the left pane shrinks again.

### Operating system
Win10 professional edition

### SQLiteStudio version
v3.2.1

**Comment by pawelsalawa** [comment] 2021-01-15 22:03
Duplicate of #3421

**Closed by pawelsalawa** 2021-01-15 22:03 UTC
