### ISSUE TITLE
Icon Mistake

### ISSUE THREAD

**Issue by albertMichel** [pawelsalawa/sqlitestudio#5186] opened 2024-12-27 16:01 UTC
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by albertMichel** [comment] 2024-12-27 16:02
The two icons are reversed.
The disk icon usually stands for save and the folder icon for open file.
![IconMistake](https://github.com/user-attachments/assets/fe9e5df7-2fb1-4f22-ae02-d5a03912c86a)

**Comment by pawelsalawa** [comment] 2024-12-27 19:44
I think it's rather German translation is inverted. I will check.

**Comment by pawelsalawa** [comment] 2024-12-27 19:46
Which SQLiteStudio version are you using? And is it "Deutsch" language that you're using?
For me it looks correctly in 3.4.12:
![image](https://github.com/user-attachments/assets/455cddce-2f7d-453e-ab41-098c373e528f)

**Comment by tuffnatty** [comment] 2024-12-27 21:52
A duplicate of #3454. Fixed both in master and 3.4.5+

**Comment by albertMichel** [comment] 2024-12-28 09:41
Great, thanks. It is displayed correctly in German with version 3.4.12.

Thank you very much.

 

Super, Danke mit Version 3.4.12 wird es in Deutsch richtig angezeigt. Vielen Dank.

 

Best regards

Albert Michel

 

Von: Paweł Salawa ***@***.***> 
Gesendet: Freitag, 27. Dezember 2024 20:47
An: pawelsalawa/sqlitestudio ***@***.***>
Cc: albertMichel ***@***.***>; Author ***@***.***>
Betreff: Re: [pawelsalawa/sqlitestudio] Icon Mistake (Issue #5186)

 

Which SQLiteStudio version are you using? And is it "Deutsch" language that you're using?
For me it looks correctly in 3.4.12:
image.png (view on web) <https://github.com/user-attachments/assets/455cddce-2f7d-453e-ab41-098c373e528f>

**Closed** 2024-12-28 10:39 UTC
Labels: bug, pending-clarification
