### ISSUE TITLE
Visualize a Database

### ISSUE THREAD

**Issue by AGoh2019** [pawelsalawa/sqlitestudio#3770] opened 2020-05-22 03:45 UTC
There is one feature which MS Access has that SQLite Studio does not provide.  And that is to visualize a database and all its relationships/tables once its created, updated, modified, truncated etc.

At the same time, I have a suggestion that a new book/tutorial be written that starts with the skill to normalize a database and its tables, before going into creating a new database.

**Comment by pawelsalawa** [comment] 2020-05-22 07:49
Duplicate of #2865 

Books/tutorials are not in scope of the project. Sorry.

**Closed by pawelsalawa** 2020-05-22 07:49 UTC
