### ISSUE TITLE
Format SQL removes single quotes

### ISSUE THREAD

**Issue by TimurMedzhitov** [pawelsalawa/sqlitestudio#4007] opened 2021-02-28 19:29 UTC
### Details
The formatting removes the single quotes surrounding text, which makes the SQL code invalid.
Note: This worked fine in previous version.

### Steps to reproduce
Type in the code in SQL editor (or open for editing a saved query that has single quotes) and select Format SQL (CMD+T):

`SELECT 'SQLite is awesome';`

### Operating system
macOS Catalina 10.15.7

### SQLiteStudio version
SQLiteStudio 3.3.0

**Comment by pawelsalawa** [comment] 2021-02-28 22:27
Looks like duplicate of #3996

**Closed by pawelsalawa** 2021-02-28 22:27 UTC

**Comment by TimurMedzhitov** [comment] 2021-03-01 00:16
Thanks, Pawel. Yes, it looks similar, mine is about single quotes, the one you mentioned is about semicolons. But they can be bundled under one tracker, of course. Thanks again.

**Comment by pawelsalawa** [comment] 2021-03-01 01:03
Actually, the other one is also about single quotes - it just happens that there is a semicolon inside, but the root problem there is removal of single quotes from around the semicolon.
