### ISSUE TITLE
The height of the watch head is incorrect

### ISSUE THREAD

**Issue by flamecyclone** [pawelsalawa/sqlitestudio#4680] opened 2023-02-03 07:12 UTC
### Details
The height of the watch head is incorrect

### Operating system
Windows 11 x64

### SQLiteStudio version
3.4.3

![image](https://user-images.githubusercontent.com/70200943/216535458-7aeb91f3-c38a-4d45-8fed-63f4324dad63.png)

**Comment by pawelsalawa** [comment] 2023-03-21 21:34
Duplicate of #4691

**Closed by pawelsalawa** 2023-03-21 21:34 UTC
Labels: bug
