### ISSUE TITLE
Version 3.4.5 to 3.4.5 - No way to change anything on table design -freezes

### ISSUE THREAD

**Issue by rebecacortazar** [pawelsalawa/sqlitestudio#5174] opened 2024-12-16 09:55 UTC
### Details
Since upgrading to version 3.4.5 to 3.4.10 I cannot change the definition of anything on any table on databases.
The same works perfectly well on version 3.4.4 (I still have in another computer).

The tool becomes block to such extent that  I must use the Task Manager to kill the process.

### Steps to reproduce
Add a database, select a table, go to Structure to edit the name of a column, for example, and everything freezes.
Even with audio signals ...

### Operating system
Windows 10 Enterprise

### SQLiteStudio version
Except 3.3.4, all the rest.

**Comment by pawelsalawa** [comment] 2024-12-17 23:50
Duplicate of #5161

**Closed** 2024-12-17 23:50 UTC
