### ISSUE TITLE
Wrong Replace Function - bug

### ISSUE THREAD

**Issue by maxxaimi** [pawelsalawa/sqlitestudio#4693] opened 2023-02-21 08:05 UTC
From 3.4.2 version
Repalce function don't work

[09:03:15] ...Error details: Error while executing SQL query on database 'DBNAME': near ")": syntax error

**Comment by tuffnatty** [comment] 2023-03-17 17:51
Duplicate of #4676.

**Closed** 2023-03-19 09:53 UTC
Labels: bug
