### ISSUE TITLE
AUTORESIZE OF THE COLUMN DATABASE

### ISSUE THREAD

**Issue by Guba666** [pawelsalawa/sqlitestudio#3694] opened 2020-03-07 08:52 UTC
this issue pertains to tthe main interface.
Every time that I clicck on a table into a database, the column database itself resizes to be very narrow. this is really annoying and should be fized.
The column widths should remain untiched but by me, if I want to change them

### Steps to reproduce
very easy: open a database, resize the column database to show the definitions of tables completely, then click on the  "Tables" label (the first under the name of the database) and the column resizes narrowly.

### Operating system
I'm using windows 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment] 2020-03-07 21:31
Duplicate of #3421

**Closed by pawelsalawa** 2020-03-07 21:31 UTC

**Comment by Guba666** [comment] 2020-03-08 09:17
My dear Pawelsalawa what I have to do now ?
Sorry for this question that seems stupid, but if this "bug" is closed what does it mean ? DO I have to wait for a fix ? Don't take me as dumb, but I'm not familiar with this Git, that is new for me.
However your application is simply formidable.
Do you have an account for a donation ?
Thanks for your patience and for your assistance.

**Comment by Guba666** [comment] 2020-03-08 16:31
BTW I docked the database/tables column on the right and now it seems that the problem doesn't occur anymore.

**Comment by pawelsalawa** [comment] 2020-03-09 08:59
The fact that it's close means the code was fixed in the current developement code base and is pending for release. Unfortunately I don't have much time recently to finalize rest of the bugs for the release and to make a release it also takes some time.

That last problem is actually my target now. I'd like to introduce full CI/CD pipeline, so there will be nightly builds with most recent codebase. Still, that requires some time & work too.
