### ISSUE TITLE
Right click in empty table crashes SQLiteStudio

### ISSUE THREAD

**Issue by quantuumsnot** [pawelsalawa/sqlitestudio#3829] opened 2020-08-08 20:59 UTC
### Details
When the user right-clicks in empty table the studio crashes

### Steps to reproduce
Create a new database
Create an empty table
Right click in the empty 'Data' -> 'Grid view' tab

### Operating system
Windows 8.1 x64

### SQLiteStudio version
3.2.1
QtVersion 5.10
SQLite version 3.24

**Comment by pawelsalawa** [comment] 2020-08-08 21:13
Duplicate of #3565

**Closed by pawelsalawa** 2020-08-08 21:13 UTC
