### ISSUE TITLE
Strange intermittent bug when running SELECT:  "1st ORDER BY term out of range - should be between 1 and 1"

### ISSUE THREAD

**Issue by GeneGeneGitHub** [pawelsalawa/sqlitestudio#4975] opened 2024-04-28 15:21 UTC
### Details
Running a SELECT query returns an error like this:
"[10:30:57] Error while executing SQL query on database 'database': 1st ORDER BY term out of range - should be between 1 and 1"

It happens even if the SELECT has no ORDER BY clause.

It happens intermittently.  Haven't spotted a reason.

I just open a new SQL Editor window and the query runs fine.

### Steps to reproduce
Can't reproduce it, but once it happens it continues to happen.  No data is returned.

### Operating system
Windows 11

### SQLiteStudio version
3.4.4

Thanks for the nice app!  I use it a LOT.  I like the more spartan interface compared to some other SQLite admin apps.

**Comment by tuffnatty** [comment] 2024-08-13 16:01
Looks like a duplicate of #4819.

**Closed** 2024-08-13 16:53 UTC
