### ISSUE TITLE
New proposal, Column title fully visible

### ISSUE THREAD

**Issue by Guba666** [pawelsalawa/sqlitestudio#3707] opened 2020-04-11 11:44 UTC
### Details
Every time I open a "data" page, the column widths are re-adjusted at the maximum length (in digits) of data, cutting the column name at that width.
Some columns may have similar names in the first characters, like "data_from_vendor" and "data_from_customers" have the same "data_from" initial part of the name.
If the contained data si small, like an integer 2 or 3 digits long, the column titles are both cut to "data_fr" and one must resize manually the column width to read entirely the column title.
An option named "resize column at the length of the title" could be introduced, to a best reading.
Also saving the column width format somewhere should be nice, not to be forced to resize the columns every time one re-open a table or a view.

**Comment by pawelsalawa** [comment] 2020-04-11 14:19
Duplicate of #3447

**Closed by pawelsalawa** 2020-04-11 14:19 UTC
