### ISSUE TITLE
Can't edit row in View. Problem Extracting ROWID

### ISSUE THREAD

**Issue by deddyhermansyah** [pawelsalawa/sqlitestudio#4551] opened 2022-11-18 03:11 UTC
### Details
VIEW problem
- DLL and Query tab become unreadable in dark mode.
- editing row failed : "[09:46:14] Cannot edit this cell. Details: The query execution mechanism had problems with extracting ROWID's properly. This might be a bug in the application. You may want to report this."

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
Windows 10 - Version 21H2
Build 19044.1826

### SQLiteStudio version
3.4.0 Portable Version.
I installed this by replacing the old 3.3.3 folder manually

**Comment by pawelsalawa** [comment] 2022-11-18 07:51
* Perhaps you need to reset colors to defaults (see configuration dialog -> look & feel -> code colors).
* Would you be able to share the problematic query that returned you this uneditable data?

**Comment by deddyhermansyah** [comment] 2022-11-21 01:38
- colors are fixed by changing style to something else ,and changed it back to Fusion Dark.
- Here is the DDL of the problematic view
`CREATE VIEW last_update AS
    SELECT platform,
           id,
           nama,
           comment,
           datetime(waktu_utc, '+420 minutes') AS Waktu_JKT
      FROM account_log
     ORDER BY waktu_utc DESC;
`
- and here is DDL of related table with no primary key
`CREATE TABLE account_log (
    platform  TEXT,
    id        TEXT,
    nama      TEXT,
    comment   TEXT,
    waktu_utc TEXT
);`
with `platform` and `id` column as non-unique index.

as long as I can remember, changing data from VIEW query is possible in previous version. but this one doesn't work anymore.

**Comment by pawelsalawa** [comment] 2022-11-21 18:06
Hm. I just created the table and the view as you provided, I populated it with some sample data and then I moved into View's "Data" tab, where I was able to edit data, no problem. Therefore I cannot reproduce this problem. Maybe you don't browse View's data in its window, but you rather query the view and you try to edit query results? If yes, then what is that query?

**Comment by audiomuze** [comment] 2024-11-09 16:58
if you run a query like ```select rowid, col1, col2, colx from table where ...```  SQLiteStudio throws: ```[16:57:38] SQLiteStudio was unable to extract metadata from the query. Results won't be editable.```

**Comment by pawelsalawa** [comment] 2024-11-13 16:35
I'm pretty sure this is fixed with #4842.

I will close this one as duplicate, even though I know this one was actually first, but since it wasn't identified as a dup before and the other one is already fixed, than this is the way to go.

**Closed by pawelsalawa** 2024-11-13 16:35 UTC
