### ISSUE TITLE
[bug] incorrect DDL output for arguments (eating apostrophes of arguments)

### ISSUE THREAD

**Issue by thewayur** [pawelsalawa/sqlitestudio#4015] opened 2021-03-04 09:18 UTC
### Details
the actual query of local date time is:
` date_created    DATETIME DEFAULT (datetime('now', 'localtime')`

but 3.3.0 DDL showing  as:
` date_created    DATETIME DEFAULT (datetime(now, localtime)`

**i.e. eating apostrophes in arguments**

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
windows

### SQLiteStudio version
3.3.0

**Comment by pawelsalawa** [comment] 2021-03-04 09:29
Duplicate of #3996
(the 3.3.1 will be released soon due to this bug, as it's critical)

**Closed by pawelsalawa** 2021-03-04 09:29 UTC
