### ISSUE TITLE
SqlIte is truncating output of string/text

### ISSUE THREAD

**Issue by aakjpe** [pawelsalawa/sqlitestudio#3935] opened 2021-02-02 11:22 UTC
I'm doing INSERT into table with a text/string column. Strings are quite long, more than 100 bytes.
But when I browse the table in SQLite the text is truncated. Not showing the whole string. Frustrating.
Edit the column shows the full string. And select from the java program also show the whole string.
Any settings in SQLiteStudio or a sql command in SQLite? To show the whole string.

Kjell P.

**Comment by pawelsalawa** [comment] 2021-02-02 12:34
Duplicate of #3269

**Closed by pawelsalawa** 2021-02-02 12:34 UTC
