### ISSUE TITLE
cannot create new database

### ISSUE THREAD

**Issue by michaels011235** [pawelsalawa/sqlitestudio#4951] opened 2024-03-06 17:38 UTC
### Details
On Debian 12: after ctrl+o to add a database, when opening the browsing dialog, I cannot create a new file. I could only select a file.

![image](https://github.com/pawelsalawa/sqlitestudio/assets/24896275/43d66ebb-ae6d-4f46-9e6f-89a7b0042307)

### Steps to reproduce
see  above

### Operating system
Debian 12

### SQLiteStudio version
3.4.4

**Comment by pawelsalawa** [comment] 2024-03-06 20:46
Isn't there a input field to enter new file name?

**Comment by tuffnatty** [comment] 2024-03-06 21:40
@pawelsalawa , a duplicate of #4796.

**Comment by pawelsalawa** [comment] 2024-03-06 23:34
Right. Closing as duplicate.

**Closed by pawelsalawa** 2024-03-06 23:34 UTC
