### ISSUE TITLE
Filter can't show result

### ISSUE THREAD

**Issue by gmuskie** [pawelsalawa/sqlitestudio#5099] opened 2024-11-12 01:44 UTC
### Details
After entering the filter text in Views, can't see any result. Not sure it is related to https://github.com/pawelsalawa/sqlitestudio/issues/4641 or not.

Before filter:
![image](https://github.com/user-attachments/assets/e5b0c646-4bcd-4125-9a2e-c967e8cc1a0f)

After filtered:
![image](https://github.com/user-attachments/assets/d92dd647-af4a-4646-b5ee-f8d3764c530c)

### Steps to reproduce
I've a view and entered the filter text in Data grid and no result after applied

### Operating system
Windows 10

### SQLiteStudio version
3.4.4

**Comment by tuffnatty** [comment] 2024-11-12 10:24
Case sensitivity problem?

**Comment by gmuskie** [comment] 2024-11-13 00:22
It's not case sensitivity issue. No matter upper case or lower case, nothing show up:

![image](https://github.com/user-attachments/assets/343224a4-77c1-41d1-b477-4af193d8d9db)

**Comment by pawelsalawa** [comment] 2024-11-13 07:09
Can you please show DDL of this table?

**Comment by gmuskie** [comment] 2024-11-14 00:26
Here you go:
`
CREATE VIEW v_switch_port_to_data_port AS
    SELECT i.description AS switch_description,
           i.hostname AS hostname_or_usage,
           s.switch_port_number AS port_no,
           x.name AS to_panel_port,
           x.jack_position AS cubicle_jack_position,
           x.firstname,
           x.lastname,
           y.category || " | " || y.description || " | " || COALESCE(y.hostname, '') || " | " || COALESCE(y.remark, '') AS to_device
      FROM switch_port s
           LEFT JOIN
           inventory i ON i.inventory_id = s.inventory_id
           LEFT JOIN
           inventory y ON y.inventory_id = s.device_id
           LEFT JOIN
           (
               SELECT d.data_port_id,
                      d.name,
                      d.jack_position,
                      j.location_name,
                      j.firstname,
                      j.lastname
                 FROM network_port AS d
                      LEFT JOIN
                      (
                          SELECT l.location_id,
                                 l.name AS location_name,
                                 e.firstname,
                                 e.lastname
                            FROM location l
                                 LEFT JOIN
                                 employee e ON e.employee_id = l.employee_id
                      )
                      j ON j.location_id = d.location_id
           )
           x ON x.data_port_id = s.data_port_id;
`

**Comment by pawelsalawa** [comment] 2024-11-14 00:35
Okay, I think I found the problem. It looks like the filter works for the 1st time when you just open the View window, but then any subsequent attempts to filter will return empty results.

**Comment by pawelsalawa** [comment] 2024-11-17 23:40
It looks like this is fixed by the way of fixing #5099. At least I can no longer reproduce it now as I have the #5099 fixed.

**Closed by pawelsalawa** 2024-11-17 23:40 UTC
Labels: bug

**Comment by gmuskie** [comment] 2024-11-18 08:52
Thanks. Will check it when 3.4.5 is ready.
