### ISSUE TITLE
Databases pane constantly resizes itself to be too small to read

### ISSUE THREAD

**Issue by dbechrd** [pawelsalawa/sqlitestudio#3421] opened 2018-09-16 06:09 UTC
### Details
Databases left pane constantly resets its width and chops off e.g. column names.

### Steps to reproduce
Open a database, expand Tables->[table name]->Columns and select any column.
Increase Databases pane width using resize arrow while hovering right border.
Click "Tables". Database pane will resize to its original width.

Before:
![image](https://user-images.githubusercontent.com/707367/45593475-31d4b500-b93c-11e8-90cf-0cc7fb5eccbb.png)

After:
![image](https://user-images.githubusercontent.com/707367/45593477-3ac58680-b93c-11e8-9a9e-6afb1502e7d9.png)

It also happens when the main window loses/regains focus, and on many other repaint events. It's very frustrating!

### Operating system
Windows 10

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment] 2018-09-21 09:34
I cannot reproduce it. Can you reproduce it on any other computer?

**Comment by BarryInOttawa** [comment] 2018-10-29 19:06
Happens top me too. all the time...EXTREMELY FRUSTRATING !

**Comment by BarryInOttawa** [comment] 2018-10-29 19:34
I had to pop-out the tables panel as a work-around. Dislodged from the main window, it keeps its set width.

**Comment by sparkyb** [comment] 2019-02-07 18:11
I'm also having this same problem

**Comment by merddyin** [comment] 2019-07-10 12:09
I have experienced this same issue on three different systems. Each was running Windows 10 x64, Enterprise Edition, build 1709, 1803, and 1809. In all instances, was using Windows Installer download option for version 3.2.1.

**Comment by quantuumsnot** [comment] 2019-07-12 12:54
Have the same issue on 3.2.1 under Windows 8.1 x64 ... So annoying

**Comment by pawelsalawa** [comment] 2019-07-14 21:24
I managed to reproduce this, but according to my observation this happens only on a fresh installation. Once you quit after first run and you start application second time, the problem disappears. Is that right for you too? I'm asking all/any people commenting here.
Could you please confirm?

I'm not saying that there is no problem, but I want to confirm whether for you it behaves the same way and also that there is a workaround for you, until I fix it - just bear with it for first run, while it will work with the second and onwards runs.

**Comment by quantuumsnot** [comment] 2019-07-15 00:05
Not exactly, at next runs the issue is still here. Managed to fix it when moved the pane to be at right side ... seems legit

**Comment by pawelsalawa** [comment] 2019-07-16 13:32
@quantuumsnot Okay, one more question - when you close SQLiteStudio and re-open it - does it maintain your last position & size of the whole SQLiteStudio window? Like if it was maximized, it starts maximized too, if it was smaller - it starts smaller, etc? Or does it lose that information?

**Comment by quantuumsnot** [comment] 2019-07-17 11:00
Yes, it remembers the position of the window, the pane and the state - closed maximized->opens maximized, but closed minimized->opens in normal window.

There's also a problem when closing the studio while still connected to a database and tab/table is opened. It opens at the last opened tab/table but can't read/write data unless I double-click on a table in the pane

**Comment by pawelsalawa** [comment] 2019-07-17 11:05
Could you please report that other issue (with read/write) as separate issue on github? I'm afraid it would get lost in comments here.

**Comment by quantuumsnot** [comment] 2019-07-17 14:22
Ok then

**Closed** 2019-07-17 17:48 UTC
Labels: bug

**Comment by orkovrr** [comment] 2019-09-23 13:56
did anyone found a way to fix it?

**Comment by pawelsalawa** [comment] 2020-09-23 14:34
It is fixed for 3.2.2 (not released yet).

**Comment by powelski** [comment] 2020-09-23 14:52
@pawelsalawa great! I can confirm that, in my case, this bug only occurred on the first launch after install.

**Comment by rikman81** [comment] 2020-10-04 18:42
Also confirming that the pane retains it's resized width after the initial launch of the program.
