### ISSUE TITLE
Databases pane won't keep adjusted width

### ISSUE THREAD

**Issue by fmc-coder** [pawelsalawa/sqlitestudio#3834] opened 2020-08-25 16:47 UTC
### Details
When I increase the width of the Databases pane and right click into it for the submenu and then click out of that menu or make a selection, the Database pane reverts back to its original size. However, if I resize it and close the app and reload it, it holds its size. I use .ini files, too, to retain user preferences. Yours reverts when I click into that pane after altering its width.

### Operating system
Linux Mint 20

### SQLiteStudio version
3.2.1

**Comment by pawelsalawa** [comment] 2020-08-25 19:34
Duplicate of #3421

**Closed by pawelsalawa** 2020-08-25 19:34 UTC
