### ISSUE TITLE
1st ORDER by term out of range

### ISSUE THREAD

**Issue by erictioh** [pawelsalawa/sqlitestudio#4865] opened 2023-09-07 07:12 UTC
### Details
Sometimes it will give me these error, and the only way to solve it is close the program and restart it then it works well, i didn't do what ordering as what the error message complaint, i think its a bug.

Error after some usage within few hours (i just use it as usual)
![image](https://github.com/pawelsalawa/sqlitestudio/assets/44055730/72830a91-3148-44fa-99bf-7c4104e68e67)

After just simply restart the app (query and database, every else untouch)
![image](https://github.com/pawelsalawa/sqlitestudio/assets/44055730/7b7d15dd-8473-4878-905b-8ecf4efa073b)

### Steps to reproduce
interminent, not sure how to reproduce

### Operating system
Win11

### SQLiteStudio version
v3.4.4

**Comment by pawelsalawa** [comment] 2023-09-09 20:16
Duplicate of #4819

**Closed by pawelsalawa** 2023-09-09 20:16 UTC
