### ISSUE TITLE
Aggregated of SELECT statements are not editable but it's pastable

### ISSUE THREAD

**Issue by SteX986** [pawelsalawa/sqlitestudio#3733] opened 2020-04-29 08:15 UTC
### Details
[10:08:36] Cannot edit this cell. Details: Cannot edit columns that are result of aggregated SELECT statements.
<Doing copy-paste of a text in selected cel, **it happens and marked blue**>
[10:08:27] Tried to commit a cell which is not editable (yet modified and waiting for commit)! This is a bug. Please report it.

### Steps to reproduce
-Use/Create a view with left join, where, group by, order by
-Copy a text from everywhere else
-Try to paste text on a (string) cell in this View. Error appears, but you can do it and it's higlighted blue
-Try to commit (obviously there will be an error)

### Operating system
Windows 10 x64 1909

### SQLiteStudio version
SQLite Studio v3.1.2
Dll of SQLite 3.31.1

**Comment by pawelsalawa** [comment] 2020-04-29 08:40
Duplicate of #3537

**Closed by pawelsalawa** 2020-04-29 08:40 UTC
