### ISSUE TITLE
Drop

### ISSUE THREAD

**Issue by AGoh2019** [pawelsalawa/sqlitestudio#3762] opened 2020-05-16 06:51 UTC
### Details
Here you describe your problem details, or proposal for enhancement.

### Steps to reproduce
This applies only to bug reports. If this is a feature request, delete this section.

### Operating system
This applies only to bug reports. If this is a feature request, delete this section.

### SQLiteStudio version
This applies only to bug reports. If this is a feature request, delete this section.

**Comment by AGoh2019** [comment] 2020-05-16 06:52
Database is open. When trying to drop database called 'proglang_tblcopy' received this feedback:
[14:50:20] Error while executing SQL query on database 'proglang_tblcopy': no such table: proglang_tblcopy

**Comment by pawelsalawa** [comment] 2020-05-16 15:02
Duplicate of #3761

**Closed by pawelsalawa** 2020-05-16 15:02 UTC
