### ISSUE TITLE
"Databases" docked panel does not retain user-specified size

### ISSUE THREAD

**Issue by DWAK-ATTK** [pawelsalawa/sqlitestudio#3475] opened 2018-12-17 23:37 UTC
### Details
Opened a SQLite3 database.  I see it in the "Databases" docked panel on the left.  The right edge of that panel allows me to resize it.  After doing so, click on a node in the Databases panel.  The panel snaps back to its old size.

### Operating system
Win 10 x64

### SQLiteStudio version
v 3.2.1

**Comment by Qomplainerz** [comment] 2019-02-07 10:00
Same here on Windows 8.1 and Linux Mint Cinnamon 19.1

**Comment by iammeat** [comment] 2019-02-12 15:25
This is also occurring on macOS 10.13 with v3.2.1

**Comment by K6TD** [comment] 2019-03-11 19:41
I also have this problem. macOS 10.14.3 v3.2.1

**Comment by boshuda** [comment] 2019-04-29 17:36
This looks like it's a duplicate of #3421

**Comment by pawelsalawa** [comment] 2019-07-14 21:17
Duplicates #3421

**Closed by pawelsalawa** 2019-07-14 21:17 UTC
Labels: bug
